on:
  push:
    branches: ["main"]
#  pull_request:
#    branches: ["main"]

jobs:
  windows-x64:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run make
      - name: Recompress zip
        run: |
          Expand-Archive -Path out/make/zip/win32/x64/*.zip -DestinationPath out/make/zip/win32/x64/
          Remove-Item -Path out/make/zip/win32/x64/*.zip
      - name: Upload Artifacts for Windows
        uses: actions/upload-artifact@v4
        with:
          name: windows_x64
          compression-level: 9
          path: out/make/zip/win32/x64/*

  windows-arm64:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }} (ARM64)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run make -- --arch=arm64 --platform=win32
      - name: Recompress zip
        run: |
          Expand-Archive -Path out/make/zip/win32/arm64/*.zip -DestinationPath out/make/zip/win32/arm64/
          Remove-Item -Path out/make/zip/win32/arm64/*.zip
      - name: Upload Artifacts for Windows (ARM64)
        uses: actions/upload-artifact@v4
        with:
          name: windows_arm64
          compression-level: 9
          path: out/make/zip/win32/arm64/*

  linux-x64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run make
      - name: Recompress zip
        run: |
          unzip -o out/make/zip/linux/x64/*.zip -d out/make/zip/linux/x64/
          rm -f out/make/zip/linux/x64/*.zip
      - name: Upload Artifacts for Linux
        uses: actions/upload-artifact@v4
        with:
          name: linux_x64
          compression-level: 9
          path: out/make/zip/linux/x64/*

  linux-arm64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }} (ARM64)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run make -- --arch=arm64 --platform=linux
      - name: Recompress zip
        run: |
          unzip -o out/make/zip/linux/arm64/*.zip -d out/make/zip/linux/arm64/
          rm -f out/make/zip/linux/arm64/*.zip
      - name: Upload Artifacts for Linux (ARM64)
        uses: actions/upload-artifact@v4
        with:
          name: linux_arm64
          compression-level: 9
          path: out/make/zip/linux/arm64/*

  macos-arm64:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }} (ARM64)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run make -- --arch=arm64 --platform=darwin
      - name: Recompress zip
        run: |
          unzip -o out/make/zip/darwin/arm64/*.zip -d out/make/zip/darwin/arm64/
          rm -f out/make/zip/darwin/arm64/*.zip
      - name: Upload Artifacts for macOS (ARM64)
        uses: actions/upload-artifact@v4
        with:
          name: macos_arm64
          compression-level: 9
          path: out/make/zip/darwin/arm64/*
